pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/RiadBRD/Library.git'
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend') {
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        failure {
            echo 'Le build a échoué'
        }
    }
}
